---
- name: Render template
  template:
    src: templates/{{ template }}
    dest: renderedconfigs/{{ hostname }}

- name: Pause for Device to Be Ready
  pause:
    seconds: 20

- name: Logging Sync
  ios_config: 
    lines: logging sync
    parents: line vty 0 4

- name: VTP Primary Server
  ios_command:
    commands:
    - command: vtp primary
      prompt: confirm
      answer: ''
  when: "'d1' in hostname"

- name: VLAN config
  ios_vlans:
    config:
    - name: HR
      vlan_id: 2
      state: active
      shutdown: disabled
    - name: Finance
      vlan_id: 3
      state: active
      shutdown: disabled
    - name: Executive
      vlan_id: 4
      state: active
      shutdown: disabled
    - name: User
      vlan_id: 5
      state: active
      shutdown: disabled
    - name: Guest
      vlan_id: 6
      state: active
      shutdown: disabled
    - name: Voice
      vlan_id: 7
      state: active
      shutdown: disabled
    - name: Management
      vlan_id: 99
      state: active
      shutdown: disabled
    state: overridden
  when: "'d' in short_hostname or 's' in short_hostname"

- name: Save config
  ios_command:
    commands: 'wr'

- name: Deploy Configuration File
  ios_command:
    commands: 
    - command: 'copy scp: startup-config'
      check_all: True
      prompt:
        - 'Address'
        - 'Source username'
        - 'Source filename'
        - 'Destination filename'
        - 'Password'
      answer:
        - '10.22.78.10'
        - '{{ linux_user }}'
        - '/home/{{ linux_user }}/CNIT450Ansible/renderedconfigs/{{ hostname }}'
        - ''
        - '{{ scp_password }}'

- name: Reboot Device
  ios_command:
    commands: 
    - command: 'reload'
      check_all: True
      prompt:
        - 'Save'
        - 'confirm'
      answer:
        - 'n'
        - ''
  ignore_errors: yes

- name: Wait for Reboot
  wait_for_connection:
    delay: 10
    timeout: 1200
  vars:
    ansible_command_timeout: 1200
