---
- name: Autoconfigure Network
  hosts: all
  serial: 25
  become: yes
  become_method: enable
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: ios
    ansible_become_password: enterprise
    become_password: enterprise
    ansible_connection: network_cli

  tasks:
  - name: Import autoconfigrole
    import_role:
      name: autoconfigrole
