---
- name: Autoconfigure Network
  hosts: all
  serial: 25
  become: yes
  become_method: enable
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Import autoconfigrole
    import_role:
      name: autoconfigrole
